trigger:
- main

pool:
  name: 'Default' # Replace Default with the name of your agent pool if you used a different pool

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --Configuration $(buildCOnfiguration)
  displayName: 'dotnet build --Configuration $(buildCOnfiguration)'
